# Generated by Django 5.0.9 on 2024-10-07 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fazenda', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, null=True)),
                ('area_total', models.IntegerField(blank=True, null=True)),
                ('area_agricultavel', models.IntegerField(blank=True, null=True)),
                ('area_vegetacao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produtores',
            },
        ),
        migrations.CreateModel(
            name='Culturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cultura', models.CharField(blank=True, null=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.produtores')),
            ],
            options={
                'db_table': 'culturas',
            },
        ),
    ]
