# Generated by Django 5.0.9 on 2024-10-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_produtores_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtores',
            name='cpfcnpj',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produtores',
            name='produtor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
