# Generated by Django 5.0.9 on 2024-10-07 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_produtores_cpfcnpj_produtores_produtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturas',
            name='produtor',
        ),
        migrations.RemoveField(
            model_name='produtores',
            name='area_agricultavel',
        ),
        migrations.RemoveField(
            model_name='produtores',
            name='area_total',
        ),
        migrations.RemoveField(
            model_name='produtores',
            name='area_vegetacao',
        ),
        migrations.RemoveField(
            model_name='produtores',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='produtores',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='produtores',
            name='fazenda',
        ),
        migrations.CreateModel(
            name='Fazendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fazenda', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cidade', models.CharField(blank=True, null=True)),
                ('area_total', models.IntegerField(blank=True, null=True)),
                ('area_agricultavel', models.IntegerField(blank=True, null=True)),
                ('area_vegetacao', models.IntegerField(blank=True, null=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.produtores')),
            ],
            options={
                'db_table': 'fazendas',
            },
        ),
        migrations.AddField(
            model_name='culturas',
            name='fazenda',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.fazendas'),
        ),
    ]
