# Generated by Django 5.0.9 on 2024-10-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_culturas_produtor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturas',
            name='fazenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culturas', to='dashboard.fazendas'),
        ),
        migrations.AlterField(
            model_name='fazendas',
            name='produtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fazendas', to='dashboard.produtores'),
        ),
    ]
